// Generated by CoffeeScript 2.3.2
(function () {
	var $, calendar_template, events_template, locations_template;
	var map_form_update = false;
	var map_loaded = false;
	$ = jQuery;

	/* vv added by stasou vv */
	var settingbounds = false;
	var all_locations = [];
	var fitbounds = false;
	var georesults = false;
	var geosuccess = false;

	window.standardBounds = {
		south: 37.285106060522345,
		west: 22.422991953125006,
		north: 38.60197072314411,
		east: 25.037738046875006,
	};

	const storesMap = $("#storesMap");
	const is_stores_map = storesMap.length;
	let stores_categories = [];
	if (is_stores_map) {
		stores_categories = JSON.parse(storesMap.val());
	}

	window.noLocations = false;
	const load_map_data = function () {
		if (!map_loaded || all_locations.length === 0) {
			if (all_locations.length === 0) {
				console.log("waiting for data");
				georesults = true;
				return setTimeout(function () {
					return load_map_data();
				}, 1000);
			}
			// console.log("data loaded");
			// var filters, province, value
			// filters = $('#map-filters');
			// province = filters.find('select:first');
			// value = province.find('option:not([value=""]):first').attr('value');
			// province.val(value);
			if (georesults && !geosuccess) {
				window.newbounds = window.standardBounds;
			}
			if (georesults) {
				$(document).trigger("geolocated");
			} else {
				setTimeout(function () {
					return load_map_data();
				}, 100);
			}

			// $('.map-container').removeClass('map-loading')
		}
	};

	var findOne = function (haystack, arr) {
		return arr.some(function (v) {
			return haystack.indexOf(v) >= 0;
		});
	};

	const logicalXOR = function (a, b) {
		return !!(a ? !b : b);
	};

	const filter_locations = function (options) {
		var return_locations, bounds;

		const is_opap_store = document.getElementById("is_opap_store").checked;
		const is_retail_store =
			document.getElementById("is_retail_store").checked;
		const filter_on_store_type = logicalXOR(is_opap_store, is_retail_store);

		var local_locations;

		if (filter_on_store_type) {
			local_locations = all_locations.filter(
				(l) => l.is_opap_store == is_opap_store
			);
		} else {
			local_locations = all_locations;
		}

		//     console.log('options')
		//     console.log(options)
		if (options.bounds) {
			if (!options.bounds.south) {
				bounds = JSON.parse(options.bounds);
			} else {
				bounds = options.bounds;
			}
			// console.log(bounds)
			return_locations = local_locations.filter(function (l) {
				return (
					((l.latitude <= bounds.north &&
						l.latitude >= bounds.south) ||
						(l.latitude >= bounds.north &&
							l.latitude <= bounds.south)) &&
					((l.longitude >= bounds.east &&
						l.longitude <= bounds.west) ||
						(l.longitude <= bounds.east &&
							l.longitude >= bounds.west))
				);
			});
		} else if (options.province) {
			return_locations = local_locations.filter(function (l) {
				return l.province == options.province;
			});
		} else {
			return_locations = local_locations;
		}

		const categories = options.categories
			? options.categories.map(function (c) {
					return parseInt(c, 10);
			  })
			: [];
		if (categories.length === 0) {
			$(".filters")
				.find("input:checked")
				.each(function () {
					categories.push(parseInt($(this).val(), 10));
				});
		}
		return_locations = return_locations.filter(function (l) {
			return findOne(l.categories, categories);
		});

		localize.locations_data = [];
		// console.log(return_locations.length);
		// console.log(return_locations)
		return return_locations;
	};

	window.filter_locations = filter_locations;
	setTimeout(function () {
		return load_map_data();
	}, 500);

	function get_initial_data() {
		let options;
		if (is_stores_map) {
			options = {
				categories: stores_categories,
				// categories: [59],
			};
		} else {
			options = {
				get_all: true,
			};
		}

		$(".map-container").addClass("map-loading");
		$.get(localize.locations_url, options).done(function (data) {
			all_locations = data.map(function (i) {
				i.categories = i.category.split(",").map(function (j) {
					return parseInt(j, 10);
				});
				i.latitude = parseFloat(i.latitude);
				i.longitude = parseFloat(i.longitude);
				return i;
			});
			window.temp_locations = data;
		});
	}

	/* ^^ added by stasou ^^ */

	calendar_template = `<div class="events-calendar">
			<div class="controls">
				<span class="clndr-previous-button fa fa-chevron-left"></span>
				<span class="month">{{ month }} {{ year }}</span>
				<span class="clndr-next-button fa fa-chevron-right"></span>
			</div>
			<div class="days-container">
				<div class="headers">
					{{#daysOfTheWeek}}
						<div class="day-header">{{ . }}</div>
					{{/daysOfTheWeek}}
				</div>
				<div class="days">
					{{#days}}
						<div class="{{ classes }}" id="{{ id }}">
							<span>{{ day }}</span>
						</div>
					{{/days}}
				</div>
			</div>
		</div>`;

	events_template = `<h2 class="date">{{{ date }}}</h2>
		<div class="categories">
			{{#categories}}
				<span class="category" data-id="{{ id }}">{{ name }}</span>
			{{/categories}}
		</div>
		<h4>{{ title }}</h4>
		<div class="events-list">
			{{#events}}
				<p class="event hide" data-category="{{ category }}">{{ time }} {{ title }}</p>
			{{/events}}
		</div>`;

	locations_template = `{{#locations}}
			<div class="location-item col-m-12 col-t-6 col-d-4 hello-my-friend">
				<h5>
					{{#is_opap_store}}
						<img src="{{ opap_store_icon }}" alt="{{ title }}" class="location-image" data-store-type="opap" />
					{{/is_opap_store}}
					{{^is_opap_store}}
						<img src="{{ other_store_icon }}" alt="{{ store_description }}" class="location-image" data-store-type="retail" />
					{{/is_opap_store}}
					{{#store_description}}
						{{{ store_description }}} |
					{{/store_description}}
					{{{ title }}}
				</h5>
				{{#image}}
					<img src="{{ image }}" alt="{{ title }}" class="location-image" />
				{{/image}}
				<div class="location-info">
					<p>{{{ address }}}, {{{ postal }}} {{{ city }}}</p>
					{{#phone}}
						<p>{{{ tel_text }}}: {{{ phone }}}</p>
					{{/phone}}
					{{#services}}
						<span class="label rounded">{{{ . }}}</span>
					{{/services}}
				</div>
				<a class="button small success" href="https://maps.google.com/?q=loc:{{latitude}}+{{longitude}}" target="_blank">
					{{{ link_text }}}
				</a>
			</div>
		{{/locations}}`;

	$.fn.equalizeGalleries = function () {
		this.attr("data-equalizer", true).attr("data-equalize-on", "medium");
		return this.find(".gallery-item").attr("data-equalizer-watch", true);
	};

	$.fn.offcanvasMenu = function () {
		return this.each(function () {
			var menu;
			menu = $(this);
			menu.find(".current-menu-parent > a").trigger("click");
			return menu.find(".current-menu-parent > ul").addClass("is-active");
		});
	};

	$.fn.eventsSchedule = function () {
		var calendar;
		calendar = $(this);
		if (!calendar.length) {
			return;
		}
		return $.get(localize.event_categories_url, function (data) {
			localize.event_categories_data = data;
			return $.get(localize.events_url, function (data) {
				localize.events_data = data;
				if (data.length) {
					return calendar.eventsCalendar();
				} else {
					return calendar.parents(".page-section:first").remove();
				}
			});
		});
	};

	$.fn.eventsCalendar = function () {
		var calendar,
			categories,
			endDate,
			events,
			eventsList,
			list,
			startDate,
			title;
		calendar = $(this);
		if (!calendar.length) {
			return;
		}
		events = localize.events_data;
		categories = localize.event_categories_data;
		title = localize.events_title;
		startDate = events[0].start;
		endDate = events[events.length - 1].end;
		list = $("#events-list");
		list.on("click", ".category", function (event) {
			var button, id;
			button = $(event.target);
			id = button.attr("data-id");
			button.siblings().removeClass("active");
			button.addClass("active");
			list.find("[data-category]").addClass("hide");
			return list
				.find('[data-category="' + id + '"]')
				.removeClass("hide");
		});
		eventsList = function (date, events) {
			var data;
			date = date.format(
				"[<span>]dddd[</span>] [<span>]D[</span>] [<span>]MMMM[</span>]"
			);
			data = {
				title: title,
				categories: categories,
				events: events,
				date: date,
			};
			list.html(Mustache.render(events_template, data));
			list.find("[data-id]").each(function () {
				var id, items;
				id = $(this).attr("data-id");
				items = list.find('[data-category="' + id + '"]');
				if (!items.length) {
					return $(this).hide();
				} else {
					return $(this).show();
				}
			});
			return list.find("[data-id]:visible:first").click();
		};
		return calendar.clndr({
			events: events,
			dateParameter: "start",
			forceSixRows: true,
			ignoreInactiveDaysInSelection: true,
			daysOfTheWeek: moment()._locale._weekdaysShort,
			constraints: {
				startDate: moment(startDate).startOf("month"),
				endDate: moment(endDate).endOf("month"),
			},
			clickEvents: {
				click: function (target) {
					var element;
					if (!target) {
						return;
					}
					element = $(target.element);
					if (target.events.length) {
						element.siblings().removeClass("active");
						element.addClass("active");
						return eventsList(target.date, target.events);
					}
				},
			},
			render: function (data) {
				return Mustache.render(calendar_template, data);
			},
			doneRendering: function () {
				return calendar.find(".day.event:first").click();
			},
			multiDayEvents: {
				endDate: "end",
				singleDay: "start",
				startDate: "start",
			},
		});
	};

	$.fn.mapLocations = function () {
		var element, filters, search;
		element = $(this);
		if (typeof google === "undefined") {
			return;
		}
		if (!element.length) {
			return;
		}
		filters = $("#map-filters");
		search = $("#map-filters .search-form");
		element.mapMarkers();
		element.mapFilters();

		element.trigger("update-markers-data", true);

		element.on("update-markers-data", function (event, fitBounds) {
			/* COMMENTED BY STASOUV
      if (!map_form_update && map_loaded ) {
        return;
      }
      map_form_update = false
      var categories, options, province, searchterm;
      categories = [];
      searchterm = search.find('input').val();
      */

			/* vv added by stasou vv */
			// if (!map_form_update && map_loaded ) {
			//   return;
			// }
			// map_form_update = false
			var categories, options, province, searchterm;
			categories = [];
			// searchterm = search.find('input').val();
			/* ^^ added by stasou ^^ */

			if (!is_stores_map) {
				filters.find("input:checked").each(function () {
					return categories.push($(this).val());
				});
			} else {
				// get the json value of storesMap and parse it and assign the array to categories array
				categories = stores_categories;
				// categories = [59];
			}

			province = filters.find("select").val();
			var get_all;
			if (!map_loaded) {
				get_all = !is_stores_map;
				map_loaded = true;
			}
			if (!categories.length) {
				localize.locations_data = [];
				return element.trigger("update-markers", fitBounds);
			} else {
				var form_bounds = window.newbounds
					? JSON.stringify(window.newbounds)
					: undefined;
				options = {
					get_all: get_all,
					bounds: form_bounds,
					categories: categories,
					province: province,
				};

				/* COMMENTED BY STASOUV
        $('.map-container').addClass('map-loading')
        return $.get(localize.locations_url, options).done(function(data) {
          localize.locations_data = data;
          $('.map-container').removeClass('map-loading')
          if (data && data.length > 0) {
            $('.map-container').removeClass('map-no-locations')
            return element.trigger('update-markers', fitBounds);
          } else if (data && data.length === 0) {
            $('.map-container').addClass('map-no-locations')
          }
          return;
        });
        */

				/* vv added by stasou vv */
				if (!window.noLocations) {
					$(".map-container").addClass("map-loading");
				}
				//
				localize.locations_data = filter_locations(options);
				fitbounds = false;
				// return $.get(localize.locations_url, options).done(function(data) {
				// localize.locations_data = data;
				// $('.map-container').removeClass('map-loading')
				// if (data && data.length > 0) {
				if (localize.locations_data) {
					$(".map-container").removeClass("map-no-locations");
					// if ( ! window.noLocations ) {
					return element.trigger("update-markers", fitBounds);
					// }
				} else if (
					localize.locations_data &&
					localize.locations_data.length === 0
				) {
					if (!window.noLocations) {
						$(".map-container").addClass("map-no-locations");
					} else {
						window.noLocations = false;
					}
					setTimeout(function () {
						$(".map-container").removeClass("map-no-locations");
						$(".map-container").removeClass("map-loading");
					}, 2500);
				}
				// return;
				// });
				/* ^^ added by stasou ^^ */
			}
		});
		return $(document).on("geolocated", function (event) {
			/* COMMENTED BY STASOUV
      return element.trigger('update-markers-data', true);
      */
			/* vv added by stasou vv */
			localize.locations_data = [];
			return element.trigger("update-markers-data", fitbounds);
			/* ^^ added by stasou ^^ */
		});
	};

	$.fn.mapMarkers = function () {
		// vv mods by stasouv
		// var addMarker, bounds, cluster_options, clusters, element, filters, geoError, geoSuccess, geocodeLatLng, geocoder, infowindow, map, map_controls, map_options, province, provinces;
		var addMarker,
			bounds,
			cluster_options,
			clusters,
			element,
			filters,
			geoError,
			geoSuccess,
			geocodeLatLng,
			geocoder,
			infowindow,
			map,
			map_controls,
			map_options,
			province,
			provinces,
			search;
		// ^^ mods by stasouv
		element = $(this);
		if (typeof google === "undefined") {
			return;
		}
		if (!element.length) {
			return;
		}
		filters = $("#map-filters");
		province = filters.find("select:first");
		// vv mods by stasouv
		search = filters.find("input");

		// ^^ mods by stasouv
		provinces = [];
		geocoder = new google.maps.Geocoder();
		province.find("option").each(function () {
			var formatted;
			formatted = $(this).attr("data-formatted");
			if (formatted) {
				return provinces.push(formatted);
			}
		});
		geocodeLatLng = function (coords) {
			return geocoder.geocode(
				{
					location: coords,
				},
				function (results, status) {
					var value;
					const valid_results = results.filter(function (a, ind) {
						return (
							ind === 0 ||
							a.types.filter(function (b) {
								return b === "postal_code";
							}).length > 0
						);
					});
					if (status === "OK") {
						var bounds = {
							south: coords.lat() - 0.01,
							north: coords.lat() + 0.01,
							east: coords.lng() - 0.01,
							west: coords.lng() + 0.01,
						};
						newbounds = bounds;
						map_form_update = true;
						// vv mods by stasouv
						const loc_formatted_address =
							valid_results[1] !== undefined
								? valid_results[1].formatted_address
								: valid_results[0].formatted_address;
						filters
							.find('input[name="s"]')
							.val(loc_formatted_address);
						// ^^ mods by stasouv
					} else {
						value = province
							.find('option:not([value=""]):first')
							.attr("value");
						province.val(value);
					}
					// vv mods by stasouv
					fitbounds = true;
					// ^^ mods by stasouv
					return $(document).trigger("geolocated");
				}
			);
		};
		/* COMMENTED BY STASOUV
    geoSuccess = function(position) {
      var user_coords;
      user_coords = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
      return geocodeLatLng(user_coords);
    };
    geoError = function() {
      var user_coords;
      user_coords = new google.maps.LatLng(geolocation.latitude, geolocation.longitude);
      return geocodeLatLng(user_coords);
    };
    navigator.geolocation.getCurrentPosition(geoSuccess, geoError);
    var bound_restrictions = localize.zoom_out_of_greece !== "allow" ? {
      latLngBounds: {
        north: 46 + 5 ,
        south: 29 - 5,
        west: 12 - 5,
        east: 36 + 5
      },
      strictBounds: true
    } : {};
    */
		// vv mods by stasouv
		geoSuccess = function (position) {
			// console.log('geoSuccess')
			georesults = true;
			geosuccess = true;
			if (all_locations.length === 0) {
				return setTimeout(function () {
					geoSuccess(position);
				}, 100);
			}
			localize.locations_data = [];
			map_loaded = true;
			filters = $("#map-filters");
			var user_coords;
			user_coords = new google.maps.LatLng(
				position.coords.latitude,
				position.coords.longitude
			);
			return geocodeLatLng(user_coords);
		};
		geoError = function () {
			georesults = true;
			// console.log('geoError')
			// var user_coords;
			// user_coords = new google.maps.LatLng(geolocation.latitude, geolocation.longitude);
			// return geocodeLatLng(user_coords);
		};
		navigator.geolocation.getCurrentPosition(geoSuccess, geoError);
		var bound_restrictions =
			localize.zoom_out_of_greece !== "allow"
				? {
						latLngBounds: {
							// was 5, is 8
							north: 46 + 8,
							south: 29 - 8,
							west: 12 - 8,
							east: 36 + 8,
						},
						strictBounds: true,
				  }
				: {};
		// ^^ mods by stasouv

		//    console.log("bound_restrictions")
		//    console.log(bound_restrictions)
		map_options = {
			zoom: 10,
			center: new google.maps.LatLng(37.9747815, 23.732726),
			mapTypeId: google.maps.MapTypeId.ROADMAP,
			scrollwheel: false,
			disableDefaultUI: false,
			streetViewControl: false,
			fullScreenControl: false,
			zoomControl: true,
			mapTypeControl: false,
			restriction: bound_restrictions,
			styles: [
				{
					featureType: "all",
					elementType: "geometry.fill",
					stylers: [{ color: "#fcfcfc" }],
				},
				{
					featureType: "administrative",
					elementType: "all",
					stylers: [{ visibility: "on" }],
				},
				{
					featureType: "administrative.country",
					elementType: "all",
					stylers: [{ visibility: "on" }],
				},
				{
					featureType: "administrative.province",
					elementType: "all",
					stylers: [{ visibility: "on" }],
				},
				{
					featureType: "landscape.natural",
					elementType: "all",
					stylers: [{ visibility: "on" }],
				},
				{
					featureType: "landscape.natural.landcover",
					elementType: "all",
					stylers: [{ visibility: "on" }],
				},
				{
					featureType: "poi.business",
					elementType: "all",
					stylers: [{ visibility: "off" }],
				},
				{
					featureType: "poi.park",
					elementType: "all",
					stylers: [{ visibility: "on" }],
				},
				{
					featureType: "poi.park",
					elementType: "geometry.fill",
					stylers: [{ color: "#fcfcfc" }],
				},
				{
					featureType: "poi.school",
					elementType: "all",
					stylers: [{ visibility: "off" }],
				},
				{
					featureType: "road",
					elementType: "all",
					stylers: [{ visibility: "on" }],
				},
				{
					featureType: "road",
					elementType: "geometry.fill",
					stylers: [{ color: "#eeeeee" }],
				},
				{
					featureType: "road.highway",
					elementType: "all",
					stylers: [{ saturation: "-100" }],
				},
				{
					featureType: "road.local",
					elementType: "all",
					stylers: [{ visibility: "on" }],
				},
				{
					featureType: "road.local",
					elementType: "geometry.stroke",
					stylers: [{ visibility: "off" }],
				},
				{
					featureType: "transit",
					elementType: "all",
					stylers: [{ visibility: "on" }],
				},
				{
					featureType: "water",
					elementType: "geometry.fill",
					stylers: [{ visibility: "on" }, { color: "#dcdcdc" }],
				},
			],
		};
		cluster_options = {
			gridSize: 50,
			maxZoom: 15,
			styles: [
				{
					url: localize.cluster_icon,
					height: 53,
					width: 53,
					textColor: "#FFFFFF",
				},
				{
					url: localize.cluster_icon,
					height: 56,
					width: 56,
					textColor: "#FFFFFF",
				},
				{
					url: localize.cluster_icon,
					height: 66,
					width: 66,
					textColor: "#FFFFFF",
				},
				{
					url: localize.cluster_icon,
					height: 78,
					width: 78,
					textColor: "#FFFFFF",
				},
				{
					url: localize.cluster_icon,
					height: 90,
					width: 90,
					textColor: "#FFFFFF",
				},
			],
		};
		map = new google.maps.Map(element[0], map_options);
		// for debugging
		window.map = map;

		var input = jQuery(".filters-search input")[0];
		var acoptions = {
			componentRestrictions: { country: "gr" },
		};
		var autocomplete = new google.maps.places.Autocomplete(
			input,
			acoptions
		);
		autocomplete.setFields([
			"address_components",
			"geometry",
			"icon",
			"name",
		]);
		autocomplete.addListener("place_changed", function () {
			$("#select-province").val("");
			var place = autocomplete.getPlace();
			if (!place.geometry) {
				// console.log(place);
				// User entered the name of a Place that was not suggested and
				// pressed the Enter key, or the Place Details request failed.

				// Fake an error to prevent dropdown from going away
				return no_place_exception;
			}

			// If the place has a geometry, then present it on a map.
			if (place.geometry.viewport) {
				$(".map-container").addClass("map-loading");
				// vv mods by stasouv
				localize.locations_data = [];
				// ^^ mods by stasouv
				window.newbounds = place.geometry.viewport;
				map.fitBounds(place.geometry.viewport);
				options = {
					bounds: JSON.stringify(place.geometry.viewport),
				};
				/* COMMENTED BY STASOUV
        return $.get(localize.locations_url, options).done(function(data) {
          localize.locations_data = data;
          $('.map-container').removeClass('map-loading')
          if (data && data.length > 0) {
            $('.map-container').removeClass('map-no-locations')
          } else if (data && data.length === 0) {
            $('.map-container').addClass('map-no-locations')
          }
          return element.trigger('update-markers');
        });
        */
				// vv mods by stasouv
				// return $.get(localize.locations_url, options).done(function(data) {
				// localize.locations_data = data;
				localize.locations_data = filter_locations(options);
				// $('.map-container').removeClass('map-loading')
				if (
					localize.locations_data &&
					localize.locations_data.length > 0
				) {
					$(".map-container").removeClass("map-no-locations");
				} else if (
					localize.locations_data &&
					localize.locations_data.length === 0
				) {
					window.noLocations = true;
					// console.log("CASE A")
					map.fitBounds(place.geometry.viewport);
					$(".map-container").addClass("map-no-locations");
					$(".map-container").removeClass("map-loading");
					setTimeout(function () {
						$(".map-container").removeClass("map-no-locations");
						map.fitBounds(place.geometry.viewport);
						// filter_locations(window.standardBounds)
					}, 2500);
				}
				window.newbounds = place.geometry.viewport;
				return element.trigger("update-markers");
				// });
				// ^^ mods by stasouv
			}
		});

		bounds = new google.maps.LatLngBounds();
		clusters = new MarkerClusterer(map, [], cluster_options);
		infowindow = new google.maps.InfoWindow({
			content: "Loading...",
		});
		map_controls = $("#map-controls").removeClass("hide").detach();
		map.controls[google.maps.ControlPosition.TOP_LEFT].push(
			map_controls[0]
		);
		// vv mods by stasouv
		var bounds_interval;
		map.addListener("bounds_changed", function () {
			// console.log("SETTING BOUNDS");
			if (window.newbounds && !settingbounds) {
				settingbounds = true;
				window.newbounds = map.getBounds();
				window.noLocations = true;
				$(document).trigger("geolocated");
				// SEARCH SHOULD NOT BE DELETED
				// if ( map.getZoom() < 12 ) {
				//   $('.filters-search').find('input[name="s"]').val('')
				// }
				bounds_interval = setTimeout(function () {
					window.fitloaded = true;
					settingbounds = false;
				}, 1000);
			}
		});
		// ^^ mods by stasouv

		addMarker = function (item) {
			var html, item_data, latLng, marker;
			latLng = new google.maps.LatLng(item.latitude, item.longitude);
			bounds.extend(latLng);
			item_data = {
				locations: [item],
				link_text: localize.map_link_text,
				tel_text: localize.map_tel_text,
				opap_store_icon: localize.opap_store_icon,
				other_store_icon: localize.other_store_icon,
			};
			// Αφαίρεση bubble Εισιτήρια Θεαμάτων
			var locx = item_data.locations[0];
			const unfiltered_services =
				locx.services instanceof Array
					? locx.services
					: Object.values(locx.services);
			locx = {
				...locx,
				services: unfiltered_services.filter(
					(s) => s !== "Εισιτήρια Θεαμάτων"
				),
			};
			item_data.locations = [locx];
			// done
			html = Mustache.render(locations_template, item_data);
			marker = new google.maps.Marker({
				position: latLng,
				title: item.address,
				icon: item.is_opap_store
					? localize.opap_store_icon
					: localize.other_store_icon,
				html: html,
			});
			marker.addListener("click", function () {
				// vv mods by stasouv
				window.newbounds = undefined;
				// ^^ mods by stasouv

				infowindow.setContent(marker.html);
				// This adds a manual bubble
				// addExtraSpanOnWindow();
				map.panTo(this.getPosition());
				var current_zoom = map.getZoom();
				if (current_zoom && current_zoom < 15) {
					function fcz() {
						map.setZoom(current_zoom);
						current_zoom++;
						if (current_zoom < 15) {
							setTimeout(fcz, 50);
						}
					}
					fcz();
				}
				return infowindow.open(map, marker);
			});
			return marker;
		};
		return element.on("update-markers", function (event, fitBounds) {
			var data, locations, markers;
			bounds = new google.maps.LatLngBounds();
			locations = $("#map-locations");
			window.markers = [];
			clusters.clearMarkers();
			$.each(localize.locations_data, function (index, item) {
				return window.markers.push(addMarker(item));
			});
			clusters.addMarkers(window.markers);
			if (fitBounds) {
				map.fitBounds(bounds, 50);
			}
			data = {
				locations: localize.locations_data,
				link_text: localize.map_link_text,
				tel_text: localize.map_tel_text,
				opap_store_icon: localize.opap_store_icon,
				other_store_icon: localize.other_store_icon,
			};
			locations.html(Mustache.render(locations_template, data));
			// vv mods by stasouv
			setTimeout(function () {
				$(".map-container").removeClass("map-loading");
			}, 300);
			// ^^ mods by stasouv

			if (locations.children().length) {
				return locations.removeClass("hide");
			} else {
				return locations.addClass("hide");
			}
		});
	};

	$.fn.mapFilters = function () {
		var filters, store_type_filters, markers, search;
		markers = $(this);
		if (!markers.length) {
			return;
		}
		filters = $("#map-filters");
		store_type_filters = $("#store-types-filters");

		search = filters.find(".search-form");
		filters.on("change", "input", function (event) {
			// vv mods by stasouv
			$(".map-container").addClass("map-loading");
			// ^^ mods by stasouv

			if ($(this).attr("name") !== "s") {
				map_form_update = true;
			}
			return markers.trigger("update-markers-data", false);
		});

		store_type_filters.on("change", "input", function (event) {
			// vv mods by stasouv
			$(".map-container").addClass("map-loading");
			// ^^ mods by stasouv

			if ($(this).attr("name") !== "s") {
				map_form_update = true;
			}
			return markers.trigger("update-markers-data", false);
		});
		/* COMMENTED BY STASOUV
    filters.on('change', 'select', function(event) {
      search.find('input').val('');
      window.newbounds = undefined
      map_form_update = true;
      return markers.trigger('update-markers-data', true);
    });
    */
		search.on("submit", function (event) {
			event.preventDefault();
			return markers.trigger("update-markers-data", true);
		});
		return search.on("change", "input", function (event) {
			return markers.trigger("update-markers-data", true);
		});
	};

	$.fn.servicesCarousel = function () {
		var carousel, initCarousel, resizeItems;
		carousel = $(this);
		if (!carousel.length) {
			return;
		}
		initCarousel = function () {
			var breakpoint;
			breakpoint = $(window).width();
			if (breakpoint < 1024) {
				return carousel.sly({
					horizontal: 1,
					itemSelector: ".slidee-item",
					itemNav: "basic",
					speed: 800,
					smart: 1,
					activeClass: "active",
					prevPage: carousel.prev(),
					nextPage: carousel.next(),
				});
			} else {
				return carousel.sly("destroy");
			}
		};
		resizeItems = function () {
			var breakpoint, width;
			width = carousel.width();
			breakpoint = $(window).width();
			if (breakpoint < 1024) {
				carousel.find(".slidee-item").css("width", width);
			} else {
				carousel.find(".slidee-item").css("width", "");
			}
			return carousel.sly("reload");
		};
		resizeItems();
		initCarousel();
		return $(window).resize(function () {
			resizeItems();
			return initCarousel();
		});
	};

	// Subservice items carousel
	$.fn.subserviceItemsCarousel = function () {
		var togglePagination;
		togglePagination = function (element) {
			var pages;
			pages = element.find(".swiper-pagination-bullet").length;
			if (pages > 1) {
				return element.addClass("has-pagination");
			} else {
				return element.removeClass("has-pagination");
			}
		};
		return this.each(function () {
			var container, swiperCarousel;
			container = $(this);
			swiperCarousel = new Swiper(container.get(0), {
				slidesPerView: 3,
				slidesPerColumn: 4,
				spaceBetween: 20,
				pagination: {
					el: ".swiper-pagination",
					clickable: true,
				},
				breakpoints: {
					1024: {
						slidesPerView: 3,
						slidesPerColumn: 3,
					},
					960: {
						slidesPerView: 2,
						slidesPerColumn: 4,
					},
					580: {
						slidesPerView: 1,
						slidesPerColumn: 4,
					},
				},
			});
			togglePagination(container);
			return $(document).on("down.zf.accordion", function () {
				swiperCarousel.update();
				return togglePagination(container);
			});
		});
	};

	$.fn.scrollToSubservice = function () {
		var item, offset;
		item = $(".accordion-item.is-active");
		if (item.length) {
			offset = item.offset().top - $("#header").height() - 50;
			return $("html, body").animate(
				{
					scrollTop: offset,
				},
				500
			);
		}
	};

	$(document).ready(function () {
		get_initial_data();
		if ($(window).width() < 640) {
			var source_div = $("#map-markers");
			var target_div = $("#map-filters");
			source_div.insertAfter(target_div);
		}
		$("#map-loader,#map-no-content").css({
			left: 0,
			width: $("#map-markers").width() + "px",
		});
		if ($(window).width()) $(".offcanvas-menu").offcanvasMenu();
		$(".post-gallery").equalizeGalleries();
		$("#events-calendar").eventsSchedule();
		$("#map-markers").mapLocations();
		$("#services-carousel").servicesCarousel();
		$(".swiper-container").subserviceItemsCarousel();
		$(document).scrollToSubservice();
		return $(document).foundation();
	});
}).call(this);

// add Extra Span Marker
// disabled, keep for archiving purpose
// function addExtraSpanOnWindow() {
// 	setTimeout(() => {
// 		const map = document.getElementById("map-markers");
// 		const locationInfoElem = map.getElementsByClassName("location-info");
// 		const slielem = locationInfoElem[0];
// 		const locationImage = map.getElementsByClassName("location-image");
// 		const slimage = locationImage[0];
// 		const spansElem = slielem.getElementsByTagName("span");
// 		for (let item of spansElem) {
// 			// console.log(item.innerText);
// 			if (item.innerText === "Πληρωμή λογαριασμών" && slimage.dataset.storeType === 'opap') {
// 				const newSpanElement = document.createElement("span");
// 				// newSpanElement.innerHTML = 'Πληρωμή στα online παιχνίδια ΟΠΑΠ';
// 				// newSpanElement.innerHTML = 'Φόρτιση (Top-up) Ηλεκτρονικού Παικτικού Λογαριασμού';
// 				newSpanElement.innerHTML =
// 					"Φόρτιση pamestoixima.gr – opaponline.gr – stoiximan.gr";
// 				slielem.appendChild(newSpanElement);
// 				newSpanElement.classList.add("label", "rounded");
// 				// newSpanElement.style.backgroundColor = "#0273A2";
// 			}
// 		}
// 	}, 250);
// }

// List

const mapLocationsElement = document.getElementById("map-locations");
const locationItems =
	mapLocationsElement.getElementsByClassName("location-item");
for (let locationItem of locationItems) {
	const locationInfoElem =
		locationItem.getElementsByClassName("location-info");
	const slielem = locationInfoElem[0];
	const locationInfoSpans = locationItem.getElementsByTagName("span");
	for (let locationSpan of locationInfoSpans) {
		if (locationSpan.innerText === "Πληρωμή λογαριασμών") {
			const newSpanElement = document.createElement("span");
			// newSpanElement.innerHTML = 'Πληρωμή στα online παιχνίδια ΟΠΑΠ';
			newSpanElement.innerHTML =
				"Φόρτιση (Top-up) Ηλεκτρονικού Παικτικού Λογαριασμού";
			slielem.appendChild(newSpanElement);
			newSpanElement.classList.add('label","rounded');
			newSpanElement.classList.remove('label","rounded');
			newSpanElement.classList.add("label", "rounded");
			// newSpanElement.style.backgroundColor = "#0273A2";
		}
	}
}

// fixed
const lcselector = document.getElementsByClassName("locations-count-selector");
const lcsELEment = lcselector[0];
const observer = new MutationObserver(function (mutations) {
	mutations.forEach(function (mutationRecord) {
		const mapLocationsElement = document.getElementById("map-locations");
		const locationItems =
			mapLocationsElement.getElementsByClassName("location-item");
		for (let locationItem of locationItems) {
			const locationInfoElem =
				locationItem.getElementsByClassName("location-info");
			const slielem = locationInfoElem[0];
			const locationInfoSpans = locationItem.getElementsByTagName("span");
			for (let locationSpan of locationInfoSpans) {
				// if (locationSpan.innerText === 'Πληρωμή στα online παιχνίδια ΟΠΑΠ') {
				if (
					locationSpan.innerText ===
					"Φόρτιση (Top-up) Ηλεκτρονικού Παικτικού Λογαριασμού"
				) {
					return;
				}
			}
			for (let locationSpan of locationInfoSpans) {
				if (locationSpan.innerText === "Πληρωμή λογαριασμών") {
					const newSpanElement = document.createElement("span");
					// newSpanElement.innerHTML = 'Πληρωμή στα online παιχνίδια ΟΠΑΠ';
					newSpanElement.innerHTML =
						"Φόρτιση (Top-up) Ηλεκτρονικού Παικτικού Λογαριασμού";
					slielem.appendChild(newSpanElement);
					newSpanElement.classList.add('label","rounded');
					newSpanElement.classList.remove('label","rounded');
					newSpanElement.classList.add("label", "rounded");
					// newSpanElement.style.backgroundColor = "#0273A2";
				}
			}
		}
	});
});
observer.observe(lcsELEment, { attributes: true, attributeFilter: ["style"] });

const windowHrefMap = window.location.href;
if (windowHrefMap.includes("1008")) {
	const checkedInputs = document.getElementById("map-filters");
	const inputsSwitch = checkedInputs.getElementsByClassName("switch-input");
	for (let input of inputsSwitch) {
		if (input.id.includes("1008")) {
			input.checked = true;
		}
	}
}
// if ( window.windowHrefMap.includes('1008')) {
//     return false;
// } else {
//     console.log('containes');
// }
