// Generated by CoffeeScript 2.3.2
(function() {
  var $, calendar_template, events_template, locations_template;
  var map_form_update = false;
  var map_loaded = false;
  $ = jQuery;

  calendar_template = '<div class="events-calendar"> <div class="controls"> <span class="clndr-previous-button fa fa-chevron-left"></span> <span class="month">{{ month }} {{ year }}</span> <span class="clndr-next-button fa fa-chevron-right"></span> </div> <div class="days-container"> <div class="headers"> {{#daysOfTheWeek}} <div class="day-header">{{ . }}</div> {{/daysOfTheWeek}} </div> <div class="days"> {{#days}} <div class="{{ classes }}" id="{{ id }}"> <span>{{ day }}</span> </div> {{/days}} </div> </div> </div>';

  events_template = '<h2 class="date">{{{ date }}}</h2> <div class="categories"> {{#categories}} <span class="category" data-id="{{ id }}">{{ name }}</span> {{/categories}} </div> <h4>{{ title }}</h4> <div class="events-list"> {{#events}} <p class="event hide" data-category="{{ category }}">{{ time }} {{ title }}</p> {{/events}} </div>';

  locations_template = '{{#locations}} <div class="location-item col-m-12 col-t-6 col-d-4"> <h5>{{{ title }}}</h5> {{#image}} <img src="{{ image }}" alt="{{ title }}" class="location-image" /> {{/image}} <div class="location-info"> <p>{{{ address }}}, {{{ postal }}} {{{ city }}}</p> {{#phone}} <p>{{{ tel_text }}}: {{{ phone }}}</p> {{/phone}} {{#services}} <span class="label rounded">{{{ . }}}</span> {{/services}} </div> <a class="button small success" href="https://maps.google.com/?q=loc:{{latitude}}+{{longitude}}" target="_blank">{{{ link_text }}}</a> </div> {{/locations}}';

  $.fn.equalizeGalleries = function() {
    this.attr('data-equalizer', true).attr('data-equalize-on', 'medium');
    return this.find('.gallery-item').attr('data-equalizer-watch', true);
  };

  $.fn.offcanvasMenu = function() {
    return this.each(function() {
      var menu;
      menu = $(this);
      menu.find('.current-menu-parent > a').trigger('click');
      return menu.find('.current-menu-parent > ul').addClass('is-active');
    });
  };

  $.fn.eventsSchedule = function() {
    var calendar;
    calendar = $(this);
    if (!calendar.length) {
      return;
    }
    return $.get(localize.event_categories_url, function(data) {
      localize.event_categories_data = data;
      return $.get(localize.events_url, function(data) {
        localize.events_data = data;
        if (data.length) {
          return calendar.eventsCalendar();
        } else {
          return calendar.parents('.page-section:first').remove();
        }
      });
    });
  };

  $.fn.eventsCalendar = function() {
    var calendar, categories, endDate, events, eventsList, list, startDate, title;
    calendar = $(this);
    if (!calendar.length) {
      return;
    }
    events = localize.events_data;
    categories = localize.event_categories_data;
    title = localize.events_title;
    startDate = events[0].start;
    endDate = events[events.length - 1].end;
    list = $('#events-list');
    list.on('click', '.category', function(event) {
      var button, id;
      button = $(event.target);
      id = button.attr('data-id');
      button.siblings().removeClass('active');
      button.addClass('active');
      list.find('[data-category]').addClass('hide');
      return list.find('[data-category="' + id + '"]').removeClass('hide');
    });
    eventsList = function(date, events) {
      var data;
      date = date.format('[<span>]dddd[</span>] [<span>]D[</span>] [<span>]MMMM[</span>]');
      data = {
        title: title,
        categories: categories,
        events: events,
        date: date
      };
      list.html(Mustache.render(events_template, data));
      list.find('[data-id]').each(function() {
        var id, items;
        id = $(this).attr('data-id');
        items = list.find('[data-category="' + id + '"]');
        if (!items.length) {
          return $(this).hide();
        } else {
          return $(this).show();
        }
      });
      return list.find('[data-id]:visible:first').click();
    };
    return calendar.clndr({
      events: events,
      dateParameter: 'start',
      forceSixRows: true,
      ignoreInactiveDaysInSelection: true,
      daysOfTheWeek: moment()._locale._weekdaysShort,
      constraints: {
        startDate: moment(startDate).startOf('month'),
        endDate: moment(endDate).endOf('month')
      },
      clickEvents: {
        click: function(target) {
          var element;
          if (!target) {
            return;
          }
          element = $(target.element);
          if (target.events.length) {
            element.siblings().removeClass('active');
            element.addClass('active');
            return eventsList(target.date, target.events);
          }
        }
      },
      render: function(data) {
        return Mustache.render(calendar_template, data);
      },
      doneRendering: function() {
        return calendar.find('.day.event:first').click();
      },
      multiDayEvents: {
        endDate: 'end',
        singleDay: 'start',
        startDate: 'start'
      }
    });
  };

  $.fn.mapLocations = function() {
    var element, filters, search;
    element = $(this);
    if (typeof google === 'undefined') {
      return;
    }
    if (!element.length) {
      return;
    }
    filters = $('#map-filters');
    search = $('#map-filters .search-form');
    element.mapMarkers();
    element.mapFilters();

    element.trigger('update-markers-data', true);

    element.on('update-markers-data', function(event, fitBounds) {

      if (!map_form_update && map_loaded ) {
        return;
      }
      map_form_update = false
      var categories, options, province, searchterm;
      categories = [];
      searchterm = search.find('input').val();
      filters.find('input:checked').each(function() {
        return categories.push($(this).val());
      });
      province = filters.find('select').val();
      var get_all;
      if (!map_loaded) {
        get_all = true;
        map_loaded = true;
      }
      if (!categories.length) {
        localize.locations_data = [];
        return element.trigger('update-markers', fitBounds);
      } else {
        var form_bounds = window.newbounds ? JSON.stringify(window.newbounds) : undefined
        options = {
          get_all: get_all,
          bounds: form_bounds,
          categories: categories,
          province: province
        };
        $('.map-container').addClass('map-loading')
        return $.get(localize.locations_url, options).done(function(data) {
          localize.locations_data = data;
          $('.map-container').removeClass('map-loading')
          if (data && data.length > 0) {
            $('.map-container').removeClass('map-no-locations')
            return element.trigger('update-markers', fitBounds);
          } else if (data && data.length === 0) {
            $('.map-container').addClass('map-no-locations')
          }
          return;
        });
      }
    });
    return $(document).on('geolocated', function(event) {
      return element.trigger('update-markers-data', true);
    });
  };

  $.fn.mapMarkers = function() {
    var addMarker, bounds, cluster_options, clusters, element, filters, geoError, geoSuccess, geocodeLatLng, geocoder, infowindow, map, map_controls, map_options, province, provinces;
    element = $(this);
    if (typeof google === 'undefined') {
      return;
    }
    if (!element.length) {
      return;
    }
    filters = $('#map-filters');
    province = filters.find('select:first');
    provinces = [];
    geocoder = new google.maps.Geocoder;
    province.find('option').each(function() {
      var formatted;
      formatted = $(this).attr('data-formatted');
      if (formatted) {
        return provinces.push(formatted);
      }
    });
    geocodeLatLng = function(coords) {
      return geocoder.geocode({
        'location': coords
      }, function(results, status) {
        var value;
        if (status === 'OK') {
          var bounds = {
            south: coords.lat() - 0.01,
            north: coords.lat() + 0.01,
            east: coords.lng() - 0.01,
            west: coords.lng() + 0.01
          }
          newbounds = bounds;
          map_form_update = true;

        } else {
          value = province.find('option:not([value=""]):first').attr('value');
          province.val(value);
        }
        return $(document).trigger('geolocated');
      });
    };
    geoSuccess = function(position) {
      var user_coords;
      user_coords = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
      return geocodeLatLng(user_coords);
    };
    geoError = function() {
      var user_coords;
      user_coords = new google.maps.LatLng(geolocation.latitude, geolocation.longitude);
      return geocodeLatLng(user_coords);
    };
    navigator.geolocation.getCurrentPosition(geoSuccess, geoError);
    var bound_restrictions = localize.zoom_out_of_greece !== "allow" ? {
      latLngBounds: {
        north: 46 + 5 ,
        south: 29 - 5,
        west: 12 - 5,
        east: 36 + 5
      },
      strictBounds: true
    } : {};
    console.log("bound_restrictions")
    console.log(bound_restrictions)
    map_options = {
      zoom: 10,
      center: new google.maps.LatLng(37.9747815, 23.732726),
      mapTypeId: google.maps.MapTypeId.ROADMAP,
      scrollwheel: false,
      disableDefaultUI: false,
      streetViewControl: false,
      fullScreenControl: false,
      zoomControl: true,
      mapTypeControl: false,
      restriction: bound_restrictions,
      styles: [{"featureType":"all","elementType":"geometry.fill","stylers":[{"color":"#fcfcfc"}]},{"featureType":"administrative","elementType":"all","stylers":[{"visibility":"on"}]},{"featureType":"administrative.country","elementType":"all","stylers":[{"visibility":"on"}]},{"featureType":"administrative.province","elementType":"all","stylers":[{"visibility":"on"}]},{"featureType":"landscape.natural","elementType":"all","stylers":[{"visibility":"on"}]},{"featureType":"landscape.natural.landcover","elementType":"all","stylers":[{"visibility":"on"}]},{"featureType":"poi.business","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"poi.park","elementType":"all","stylers":[{"visibility":"on"}]},{"featureType":"poi.park","elementType":"geometry.fill","stylers":[{"color":"#fcfcfc"}]},{"featureType":"poi.school","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"road","elementType":"all","stylers":[{"visibility":"on"}]},{"featureType":"road","elementType":"geometry.fill","stylers":[{"color":"#eeeeee"}]},{"featureType":"road.highway","elementType":"all","stylers":[{"saturation":"-100"}]},{"featureType":"road.local","elementType":"all","stylers":[{"visibility":"on"}]},{"featureType":"road.local","elementType":"geometry.stroke","stylers":[{"visibility":"off"}]},{"featureType":"transit","elementType":"all","stylers":[{"visibility":"on"}]},{"featureType":"water","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"color":"#dcdcdc"}]}]
    };
    cluster_options = {
      gridSize: 50,
      maxZoom: 15,
      styles: [
        {
          url: localize.cluster_icon,
          height: 53,
          width: 53,
          textColor: '#FFFFFF'
        },
        {
          url: localize.cluster_icon,
          height: 56,
          width: 56,
          textColor: '#FFFFFF'
        },
        {
          url: localize.cluster_icon,
          height: 66,
          width: 66,
          textColor: '#FFFFFF'
        },
        {
          url: localize.cluster_icon,
          height: 78,
          width: 78,
          textColor: '#FFFFFF'
        },
        {
          url: localize.cluster_icon,
          height: 90,
          width: 90,
          textColor: '#FFFFFF'
        }
      ]
    };
    map = new google.maps.Map(element[0], map_options);
    // for debugging
    window.map = map;

    var input = jQuery('.filters-search input')[0]
    var acoptions =  {
      componentRestrictions: {country: "gr"}
     };
    var autocomplete = new google.maps.places.Autocomplete(input, acoptions);
    autocomplete.setFields(['address_components', 'geometry', 'icon', 'name']);
    autocomplete.addListener('place_changed', function() {
      $('#select-province').val('')
      var place = autocomplete.getPlace();
      if (!place.geometry) {
        console.log(place)
        // User entered the name of a Place that was not suggested and
        // pressed the Enter key, or the Place Details request failed.

        // Fake an error to prevent dropdown from going away
        return no_place_exception;
      }

      // If the place has a geometry, then present it on a map.
      if (place.geometry.viewport) {
        window.newbounds = place.geometry.viewport
        map.fitBounds(place.geometry.viewport);
        $('.map-container').addClass('map-loading')
        options = {
          bounds: JSON.stringify(place.geometry.viewport)
        }
        return $.get(localize.locations_url, options).done(function(data) {
          localize.locations_data = data;
          $('.map-container').removeClass('map-loading')
          if (data && data.length > 0) {
            $('.map-container').removeClass('map-no-locations')
          } else if (data && data.length === 0) {
            $('.map-container').addClass('map-no-locations')
          }
          return element.trigger('update-markers');
        });
      }
    });

    bounds = new google.maps.LatLngBounds();
    clusters = new MarkerClusterer(map, [], cluster_options);
    infowindow = new google.maps.InfoWindow({
      content: 'Loading...'
    });
    map_controls = $('#map-controls').removeClass('hide').detach();
    map.controls[google.maps.ControlPosition.TOP_LEFT].push(map_controls[0]);
    addMarker = function(item) {
      var html, item_data, latLng, marker;
      latLng = new google.maps.LatLng(item.latitude, item.longitude);
      bounds.extend(latLng);
      item_data = {
        locations: [item],
        link_text: localize.map_link_text,
        tel_text: localize.map_tel_text
      };
      html = Mustache.render(locations_template, item_data);
      marker = new google.maps.Marker({
        position: latLng,
        title: item.address,
        icon: localize.map_marker,
        html: html
      });
      marker.addListener('click', function() {
        infowindow.setContent(marker.html);
        map.panTo(this.getPosition());
        var current_zoom = map.getZoom();
        if (current_zoom && current_zoom < 15) {
          function fcz() {
              map.setZoom(current_zoom);
              current_zoom++;
              if( current_zoom < 15 ){
                  setTimeout( fcz, 50 );
              }
          }
          fcz();
        }
        return infowindow.open(map, marker);
      });
      return marker;
    };
    return element.on('update-markers', function(event, fitBounds) {
      var data, locations, markers;
      bounds = new google.maps.LatLngBounds();
      locations = $('#map-locations');
      window.markers = [];
      clusters.clearMarkers();
      $.each(localize.locations_data, function(index, item) {
        return window.markers.push(addMarker(item));
      });
      clusters.addMarkers(window.markers);
      if (fitBounds) {
        map.fitBounds(bounds, 50);
      }
      data = {
        locations: localize.locations_data,
        link_text: localize.map_link_text,
        tel_text: localize.map_tel_text
      };
      locations.html(Mustache.render(locations_template, data));
      if (locations.children().length) {
        return locations.removeClass('hide');
      } else {
        return locations.addClass('hide');
      }
    });
  };

  $.fn.mapFilters = function() {
    var filters, markers, search;
    markers = $(this);
    if (!markers.length) {
      return;
    }
    filters = $('#map-filters');
    search = filters.find('.search-form');
    filters.on('change', 'input', function(event) {
      if ($(this).attr('name') !== "s") {
        map_form_update = true
      }
      return markers.trigger('update-markers-data', false);
    });
    filters.on('change', 'select', function(event) {
      search.find('input').val('');
      window.newbounds = undefined
      map_form_update = true;
      return markers.trigger('update-markers-data', true);
    });
    search.on('submit', function(event) {
      event.preventDefault();
      return markers.trigger('update-markers-data', true);
    });
    return search.on('change', 'input', function(event) {
      return markers.trigger('update-markers-data', true);
    });
  };

  $.fn.servicesCarousel = function() {
    var carousel, initCarousel, resizeItems;
    carousel = $(this);
    if (!carousel.length) {
      return;
    }
    initCarousel = function() {
      var breakpoint;
      breakpoint = $(window).width();
      if (breakpoint < 1024) {
        return carousel.sly({
          horizontal: 1,
          itemSelector: '.slidee-item',
          itemNav: 'basic',
          speed: 800,
          smart: 1,
          activeClass: 'active',
          prevPage: carousel.prev(),
          nextPage: carousel.next()
        });
      } else {
        return carousel.sly('destroy');
      }
    };
    resizeItems = function() {
      var breakpoint, width;
      width = carousel.width();
      breakpoint = $(window).width();
      if (breakpoint < 1024) {
        carousel.find('.slidee-item').css('width', width);
      } else {
        carousel.find('.slidee-item').css('width', '');
      }
      return carousel.sly('reload');
    };
    resizeItems();
    initCarousel();
    return $(window).resize(function() {
      resizeItems();
      return initCarousel();
    });
  };

  // Subservice items carousel
  $.fn.subserviceItemsCarousel = function() {
    var togglePagination;
    togglePagination = function(element) {
      var pages;
      pages = element.find('.swiper-pagination-bullet').length;
      if (pages > 1) {
        return element.addClass('has-pagination');
      } else {
        return element.removeClass('has-pagination');
      }
    };
    return this.each(function() {
      var container, swiperCarousel;
      container = $(this);
      swiperCarousel = new Swiper(container.get(0), {
        slidesPerView: 3,
        slidesPerColumn: 4,
        spaceBetween: 20,
        pagination: {
          el: '.swiper-pagination',
          clickable: true
        },
        breakpoints: {
          1024: {
            slidesPerView: 3,
            slidesPerColumn: 3
          },
          960: {
            slidesPerView: 2,
            slidesPerColumn: 4
          },
          580: {
            slidesPerView: 1,
            slidesPerColumn: 4
          }
        }
      });
      togglePagination(container);
      return $(document).on('down.zf.accordion', function() {
        swiperCarousel.update();
        return togglePagination(container);
      });
    });
  };

  $.fn.scrollToSubservice = function() {
    var item, offset;
    item = $('.accordion-item.is-active');
    if (item.length) {
      offset = (item.offset().top - $('#header').height()) - 50;
      return $('html, body').animate({
        scrollTop: offset
      }, 500);
    }
  };


  $(document).ready(function() {
    if ($(window).width() < 640 ) {
      var source_div = $('#map-markers')
      var target_div = $('#map-filters')
      source_div.insertAfter(target_div)
    }
    $('#map-loader,#map-no-content').css({
      'left': 0,
      'width': $('#map-markers').width() + 'px'
    })
    if ($(window).width())
    $('.offcanvas-menu').offcanvasMenu();
    $('.post-gallery').equalizeGalleries();
    $('#events-calendar').eventsSchedule();
    $('#map-markers').mapLocations();
    $('#services-carousel').servicesCarousel();
    $('.swiper-container').subserviceItemsCarousel();
    $(document).scrollToSubservice();
    return $(document).foundation();
  });

}).call(this);
